server:
  port: 8080

spring:
  application:
    name: lib-seat-back
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pub-test.milolab.cn:3306/seat?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia
    /Shanghai
    username: admin
    password: milowang2020

mybatis:
  type-aliases-package: cn.alipapa.seat.bean
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn:
      alipapa:
        seat:
          dao: debug
